#!/bin/bash -l

#$ -P noc-lab
#$ -N routing_rebalancing
#$ -j y
#$ -m bae
#$ -pe omp 32
#$ -l mem_per_core=10G
#$ -l h_rt=24:00:00

# Load Modules
module load python3
module load gurobi/9.0.0

# Run program
python3 -m experiments.run_penRate_intermodal_journal
